import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from './components/Navbar';
import Provider from '@/service/provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className} id='root'>
        <Provider attribute='class' defaultTheme='system' enableSystem>
          <div className='w-full max-w-screen-2xl' id='root'>
            <Navbar />
            {children}
          </div>
        </Provider>
      </body>
    </html>
  );
}
